### ISSUE TITLE
Option to disable cython

### ISSUE THREAD

**Issue by oberstet** [Iotic-Labs/py-ubjson#2]
Could we have an option to disable building of Cython extension modules? Like an env var `UBJSON_NO_EXTENSION=1`?

**Comment by vtermanis** [comment]
Does the referenced commit on the dev-contrib branch do what you're looking for?

**Comment by oberstet** [comment]
@vtermanis Yep, cool! That would do.

**Comment by vtermanis** [comment]
I'm a bit busy at the moment but I'll make a new PyPI release probably this Wednesday (assuming fix for #1 also works).

**Comment by oberstet** [comment]
Awesome! Thanks for quick fixes. Yes, can confirm, the other one does also work.

**Comment by oberstet** [comment]
FWIW, all our unit tests pass now using the dev branch:

* https://travis-ci.org/crossbario/autobahn-python/builds/123966197 
* eg https://travis-ci.org/crossbario/autobahn-python/jobs/123966206#L442
* payloads: https://github.com/crossbario/autobahn-python/blob/master/autobahn/wamp/test/test_serializer.py#L37

We'll move to the new release when it's on PyPI .. until then https://github.com/crossbario/autobahn-python/blob/master/tox.ini#L27

Thanks!

**Comment by vtermanis** [comment]
Available in [v0.8.4](https://github.com/Iotic-Labs/py-ubjson/releases/tag/v0.8.4)

**Comment by oberstet** [comment]
Thanks for quick release! We'll have UBJSON via `py-ubjson` support in AutobahnPython and Crossbar.io in the next releases.

**Comment by vtermanis** [comment]
You're welcome. The WebSocket framework in AutobahnPython might useful to us in the near future (depending on internal priorities).
